version: '3.8'

services:
  api:
    container_name: challenge_api
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: uvicorn api.main.routes.api_route:app --host 0.0.0.0 --port ${API_PORT:-8000} --reload
    volumes:
      - .:/app/
    ports:
      - "${API_PORT:-8000}:8000"
    env_file:
      - ./.env.dev
